// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ebank;

import com.ebank.TimerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TimerDataOnDemand_Roo_Configurable {
    
    declare @type: TimerDataOnDemand: @Configurable;
    
}
